[project]
name = "data-pipelines"
version = "0.1.0"
description = "Build data pipelines"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "logging>=0.4.9.6",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
]
